# Generated by Django 5.0.3 on 2024-05-09 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_carttable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartTable',
        ),
    ]
